export { default as Hero } from "./hero"
// export { default as Features } from "./features"
// export { default as Platforms } from "./platforms"
// export { default as Pricing } from "./pricing"
// export { default as Testimonials } from "./testimonials"
